config/routes.rb
Rails.application.routes.draw do
  get 'home_pages/new'
  get 'home_pages/create'
  get 'home_pages/edit'
  get 'home_pages/delete'
  get 'home_pages/show'
  resources :locations
  resources :home_pages do
    collection do
      get 'contact'
      get 'about'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # just a demo page for how to create a map
  get "map", to: "map#index"
  
  # testing for inventory interactivity
  get "inventories", to: "map#inventories"


  # Defines the root path route ("/")
  #root "locations#index"
  root "home_pages#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
    # validates :name, :street, :state_province, :country
    geocoded_by :full_address
    after_validation :geocode
    def full_address
        "#{street}, #{city}, #{state_province}, #{country}"
      end

   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Location was successfully created." }
        format.json { render :show, status: :created, contact: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def delete
  end

  def show
  end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
  end

  def edit
  end

  def delete
  end

  def show
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]

  # GET /locations or /locations.json
  def index
    if params[:place].present?
      @locations = Location.near(params[:place], params[:distance] || 10, order: :distance)
    else
      @locations = Location.all
    end
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to location_url(@location), notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to location_url(@location), notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy!

    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:name, :street, :city, :state_province, :country, :directions)
    end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  @@mapbox_access_token = ENV['MAPBOX_ACCESS_TOKEN']
 
  def index
    @mapbox_token = @@mapbox_access_token
  end

  def inventories
    @mapbox_token = @@mapbox_access_token
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/views/contact/delete.html.erb
<h1>Contact#delete</h1>
<p>Find me in app/views/contact/delete.html.erb</p>

app/views/contact/edit.html.erb
<h1>Contact#edit</h1>
<p>Find me in app/views/contact/edit.html.erb</p>

app/views/contact/index.html.erb
<h1>Contact#index</h1>
<p>Find me in app/views/contact/index.html.erb</p>

app/views/contact/new.html.erb
<h1>Contact#new</h1>
<p>Find me in app/views/contact/new.html.erb</p>

app/views/contact/show.html.erb
<h1>Contact#show</h1>
<p>Find me in app/views/contact/show.html.erb</p>

app/views/home_pages/about.html.erb
<h1>This is About Page</h1>

<%= link_to "Back" , home_pages_path %>

app/views/home_pages/contact.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css' %>
  <style>
  html{
    background-color: white
  }
  ::placeholder {
        color: #999; /* Change placeholder color to gray */
    }
    label span{
        color: red;
    }
  </style>
</head>

<body>
   <div class="container is-flex-column mt-6">
        <h1 class="title is-1 has-text-centered has-text-black">Contact Us</h1>
        <div class="is-flex is-justify-content-center"><a href="https://github.com/anabel12345/educate-hacks-free-period-products/tree/main" class="title is-4 has-text-centered has-text-success">GitHub Repository</a></div>
        <label class="label has-text-black has-text-weight-light">Name <span>*</span></label>
        <input class="input is-small has-background-white has-text-black" placeholder="Enter your Name" type="text"> 
        <label class="label has-text-black has-text-weight-light">Email <span>*</span></label>
        <input class="input is-small has-background-white has-text-black" placeholder="Enter your Email" type="email"> 
        <label class="label has-text-black has-text-weight-light">Message <span>*</span></label>
        <textarea class="textarea is-small has-background-white has-text-black"  placeholder="Enter your text"></textarea>
        
        <div class="is-flex">
            <button class="button has-background-link mt-3">Submit</button>
            <div class="mt-3"><%=link_to "Back", home_pages_path%></div>
        </div>
   </div>
</body>

app/views/home_pages/delete.html.erb
<h1>HomePage#delete</h1>
<p>Find me in app/views/home_page/delete.html.erb</p>

app/views/home_pages/edit.html.erb
<h1>HomePage#edit</h1>
<p>Find me in app/views/home_page/edit.html.erb</p>

app/views/home_pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css' %>
  <style>
  html{
    background-color: white
  }
  </style>
</head>

<body class="has-background-white">
  <div class="container"> <!-- Add Bulma container class for content -->
    <h1 class="title is-1 has-text-black">This is Home Page</h1>
    <h1>Hello again</h1>
    <div class="is-flex ">
        <%= render 'locations/index'%>
        <%= link_to "Location", new_location_path , class: "button has-background-grey" %>
        <%= link_to "Contact", contact_home_pages_path, class: "button has-background-primary" %>
        <%= link_to "About", about_home_pages_path, class: "button has-background-success" %>
    </div>
  </div>
</body>

app/views/home_pages/new.html.erb
<h1>New location</h1>

<%= render "contact", contact: @contact %>

<br>

app/views/home_pages/show.html.erb
<h1>HomePage#show</h1>
<p>Find me in app/views/home_page/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EducateHacksFpp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location) do |form| %>
  <% if location.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :street, style: "display: block" %>
    <%= form.text_field :street %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state_province, style: "display: block" %>
    <%= form.text_field :state_province %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :directions, style: "display: block" %>
    <%= form.text_field :directions %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/_index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Locations</h1>

<%= form_with url: locations_path, method: :get do |form| %>
  <%= form.text_field :place, value: params[:place] %>
  <%= form.select :distance, [1,5,10, 50,100,500,1000], selected: params[:distance] %>
  <%= form.submit %>
<% end %>

<div id="locations">
  <% if @locations.present? %>
    <% @locations.each do |location| %>
      <%= render location %>
      <p>
        <%= link_to "Show this location", location %>
      </p>
    <% end %>
  <% else %>
    <p>No locations found.</p>
  <% end %>
</div>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <p>
    <strong>Name:</strong>
    <%= location.name %>
  </p>

  <p>
    <strong>Street:</strong>
    <%= location.street %>
  </p>

  <p>
    <strong>City:</strong>
    <%= location.city %>
  </p>

  <p>
    <strong>State province:</strong>
    <%= location.state_province %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= location.country %>
  </p>

  <p>
    <strong>Directions:</strong>
    <%= location.directions %>
  </p>

</div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Show this location", @location %> |
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Locations</h1>

<%= form_with url: locations_path, method: :get do |form| %>
  <%= form.text_field :place, value: params[:place] %>
  <%= form.select :distance, [1,5,10, 50,100,500,1000], selected: params[:distance] %>
  <%= form.submit %>
<% end %>

<div id="locations">
  <% @locations.each do |location| %>
    <%= render location %>
    <p>
      <%= link_to "Show this location", location %>
    </p>
  <% end %>
</div>

<%= link_to "New location", new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @location %>

<div>
  <%= link_to "Edit this location", edit_location_path(@location) %> |
  <%= link_to "Back to locations", locations_path %>

  <%= button_to "Destroy this location", @location, method: :delete %>
</div>

app/views/map/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mapbox Canvas</title>
  <script src="https://api.mapbox.com/mapbox-gl-js/v3.2.0/mapbox-gl.js"></script>
  <link href="https://api.mapbox.com/mapbox-gl-js/v3.2.0/mapbox-gl.css" rel="stylesheet" />
  <style>
    #map { position: absolute; top: 0; bottom: 0; width: 100%; }
  </style>
</head>
<body>
  <div id="map"></div>
  <script>
      // will this leak on page?
      mapboxgl.accessToken = "<%= @mapbox_token %>";
      const map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v11',
        center: [-74.5, 40],
        zoom: 14
      });
      // Iterate over locations and add markers
      <%= raw @locations.to_json.each do |location| %>
        new mapboxgl.Marker()
        .setLngLat([<%= location.longitude %>, <%= location.latitude %>])
        .addTo(map);
      <% end %>
  </script>
</body>
</html>

app/views/map/inventories.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css' %>
  <script src='https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.css' rel='stylesheet' />
  <style>
    .map-popup {
      max-width: 200px;
    }
  </style>
</head>


<body>
  <section class="section">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-half">
          <h1 class="title has-text-centered">👋 Flow Aid</h1>
        </div>
      </div>
      <div class="columns is-centered">
        <div class="column is-half">
          <div id='map' style='width: 100%; height: 400px; margin-bottom: 1.5rem;'></div>
        </div>
      </div>
      <div class="columns is-centered">
        <div class="column is-half">
          <form id="item-form">
            <div class="field">
              <label class="label">Item Name</label>
              <div class="control">
                <input class="input" id="item-name" type="text" placeholder="Item Name" required>
              </div>
            </div>
            <div class="field">
              <label class="label">Quantity</label>
              <div class="control">
                <input class="input" id="quantity" type="number" placeholder="Quantity" required>
              </div>
            </div>
            <div class="field is-grouped">
              <div class="control">
                <input class="input" id="latitude" type="text" placeholder="Latitude" required>
              </div>
              <div class="control">
                <input class="input" id="longitude" type="text" placeholder="Longitude" required>
              </div>
              <div class="control">
                <button class="button is-primary" id="add-item">Add Item</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>

</body>
<script>
    function getPopupHTML (latlong, name, qty) {
      // Destructuring latitude and longitude from latlong array
      const [lat, long] = latlong;

      // Template for the popup content
      const formattedHTML = `
          <div class="popup">
              <h3 class="popup-title">${name}</h3>
              <p class="popup-info">Location: ${lat}, ${long}</p>
              <p class="popup-info">Quantity: ${qty}</p>
          </div>
      `;
      
      return formattedHTML;
    };

    mapboxgl.accessToken = "<%= @mapbox_token %>";
    let initCoords = [-74.5, 40];
    let map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v11',
      center: initCoords,
      zoom: 9
    });
    
    // Initial marker
    let marker = new mapboxgl.Marker()
      .setLngLat(initCoords)
      .addTo(map);

    // popup for the marker
    let initName = "Sanitary Pads";
    let initQty = 100;

    let popup = new mapboxgl.Popup({
        className: 'map-popup'
    }).setHTML(
      getPopupHTML(initCoords, initName, initQty)
    );
    marker.setPopup(popup);

    // Event listener for form submission
    document.getElementById('item-form').addEventListener('submit', function(event) {
      event.preventDefault(); // Prevent default form submission
      let latitude = parseFloat(document.getElementById('latitude').value);
      let longitude = parseFloat(document.getElementById('longitude').value);
      let itemName = document.getElementById('item-name').value;
      let quantity = document.getElementById('quantity').value;

      // Add marker for new item
      let newMarker = new mapboxgl.Marker()
        .setLngLat([longitude, latitude])
        .addTo(map);

      let newPopup = new mapboxgl.Popup({
        className: 'map-popup'
      }).setHTML(
        getPopupHTML([longitude, latitude], itemName, quantity)
      );
      newMarker.setPopup(newPopup);

      // You can also clear the form fields if needed
      document.getElementById('latitude').value = '';
      document.getElementById('longitude').value = '';
      document.getElementById('item-name').value = '';
      document.getElementById('quantity').value = '';
    });
    

</script>